Implementation of multiswap SDK for cosmwasm
ferrumnet/MultiSwap pull request #3
Opened 2022-11-09 12:06 UTC by jpine3528

- Add readme for SDK specification
- Implement MultiswapContract interactor in Javascript for cosmwasm
- Add test script for checking multiswap contract interaction

2022-11-15 09:11 UTC, salmanferrum requested changes

2022-11-17 12:38 UTC, jpine3528 commented on scripts/sdk/README.md
> -### addFoundryAsset
It's done

2022-11-17 12:38 UTC, jpine3528 commented on scripts/sdk/README.md
> -### withdraw
It's done.

2022-11-17 12:45 UTC, salmanferrum approved these changes

2022-11-17 12:46 UTC, salmanferrum approved these changes

2022-11-18 20:45 UTC, taha-abbasi approved these changes

2022-11-18 20:45 UTC, merged