Liquidity Management and Cancellation of Failed Withdrawals
ferrumnet/MultiSwap pull request #44
Opened 2024-02-21 11:51 UTC by salmanferrum

## Overview

This pull request introduces enhancements and features to the `FundManager` contract, specifically related to the liquidity management and cancellation of failed withdrawals. The notable changes include:

#### FundManager Contract Changes:
1. **New Modifiers:**
   - `onlySettlementManager`: A modifier allowing only the designated `settlementManager` to execute certain functions. It checks if the sender is equal to the `settlementManager` address.
   - `onlyLiquidityManager`: A modifier allowing only designated liquidity managers (`liquidityManager` or `liquidityManagerBot`) to execute certain functions. It ensures that the sender is either the primary or secondary liquidity manager.

2. **New Setter Functions:**
   - `setSettlementManager`: A setter function to set the address of the settlement manager.
   - `setLiquidityManagers`: A setter function to set the addresses of the primary and secondary liquidity managers.
   - `setLiquidityManagerWithdrawal`: A setter function to set the withdrawal addresses for the liquidity manager and bot.

3. **New Cancel Withdrawal Functions (Settlement Engine Related):**
   - `cancelFailedWithdrawSigned`: A function to cancel a signed token withdrawal initiated by the router. Only the `settlementManager` can execute this function. This helps in managing failed withdrawal transactions within the context of the settlement engine.
   - `cancelFailedWithdrawSignedOneInch`: A function to cancel a signed OneInch token withdrawal initiated by the router. Similar to the previous function, it's exclusive to the `settlementManager` and is designed to handle failed OneInch token withdrawals within the settlement engine.

4. **New Event:**
   - `FailedWithdrawalCancelled`: A new event emitted when a withdrawal is canceled. It provides information about the canceled withdrawal, including the settlement manager, recipient, token, amount, and salt.

#### Additional Changes:
- **Natspecs Corrections:** Corrected and added NatSpec comments in the `FiberRouter` and `FundManager` contract for improved documentation and readability.
- **Configuration Script:** Added a new script (`configContracts.js`) for calling the configuration-related functions of multiswap contracts. This script facilitates the configuration process and ensures smooth interaction with the contracts.

2024-02-22 15:00 UTC, taha-abbasi requested changes
@salmanferrum Let's simplify the flow by having only one withdrawal address configured. The withdrawal address is only to be configured by the owner. 

Remove any logic that checks for the bot vs manager to route the withdrawal to the correct address, as this will not be needed. 

We will assign the manager role to a multi-sig and the bot, so both can call the withdrawal function, and the funds will go to the single configured address.

2024-02-22 15:15 UTC, taha-abbasi commented on contracts/multiswap-contracts/FundManager.sol
> +     * @dev Adds liquidity for the specified token, managed exclusively by liquidity managers.
We are getting rid of `addLiquidityByManager` because we can simply send tokens to the contract to refill it.

2024-02-22 17:02 UTC, naiemk approved these changes

2024-02-28 17:13 UTC, taha-abbasi commented
Approved by @naiemk

2024-02-28 17:13 UTC, merged